dependencies:
  - pip
  - python
  - pip:
    - numpy
    - pandas
    - streamlit
    - matplotlib
    - streamlit-option-menu
    - deta
    - ipykernel
    - jupyter
    - reportlab
    - sqlalchemy

name: streamlit-env